config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  root 'dashboard#show'

  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker

  passwordless_for :users, controller: 'sessions'

  constraints Passwordless::Constraint.new(User) do # rubocop:disable Metrics/BlockLength
    get 'dashboard' => 'dashboard#show'

    resources :users, except: :destroy do
      resources :user_statuses, except: %i[index show]
    end

    resources :attendances, only: %i[index edit new create update] do
      patch :quick_update
    end

    resource :attendance do
      post :quick_create
    end

    namespace :calendar_events do
      resource :syncs, only: :create
    end

    resources :calendar_events, only: [:show] do
      resource :attendance, only: [] do
        resources :excuses, only: %i[new create], controller: 'calendar_events/attendances/excuses' do
          post :accept
        end
        resource :attendance, only: :create, controller: 'calendar_events/attendances/attendances'
      end
    end

    resources :song_lists do
      resources :song_list_items
      resources :song_media_bundle_downloads, only: %i[create show]

      resources :programs, only: %i[create destroy]
    end

    resources :songs do
      resources :song_media, only: %i[new create destroy]
      resource :score, only: %i[new create edit update destroy]
    end

    resources :name_guesses, only: %i[new create]

    resources :feedbacks, only: %i[new create]

    resources :profiles, only: :index

    resources :statistics, only: :index

    resources :infos, except: %i[destroy show]

    resource :search, only: :show

    mount MissionControl::Jobs::Engine, at: '/jobs'
  end

  get '*path' => redirect('/users/sign_in'), via: :all, constraints: lambda { |req|
    req.path.exclude? 'rails/'
  }
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  PAST_EVENTS_COUNT = 5

  def show
    @calendar_events = if params[:load_past] == 'true'
                         CalendarEvent.past_n(PAST_EVENTS_COUNT) + CalendarEvent.next
                       else
                         CalendarEvent.next
                       end

    @attendance_checks = @calendar_events.index_with { |ce| AttendanceRestrictionCheck.new(current_user, ce) }

    @overview_calendar_events = CalendarEvent.where(starts_at: AttendancePagination.new.current_range)
    @upcoming_birthdays = upcoming_birthdays
    @info = Info.newest_active.first
  end

  private

  def upcoming_birthdays
    upcoming_birthdays_query.to_h { |e| [User.find(e.id), Date.parse(e.next_birthday)] }
  end

  def upcoming_birthdays_query
    User.select(
      'users.id', "
    CASE
      WHEN strftime('%m-%d', birth_date) >= strftime('%m-%d', 'now')
      THEN date(strftime('%Y', 'now') || '-' || strftime('%m-%d', birth_date))
      ELSE date((strftime('%Y', 'now') + 1) || '-' || strftime('%m-%d', birth_date))
    END AS next_birthday"
    ).joins(:user_statuses).where(
      'user_statuses.id IN (?) AND users.birth_date IS NOT NULL', active_user_status_ids
    ).order(next_birthday: :asc).limit(5)
  end

  def active_user_status_ids
    UserStatus.not_inactive.valid_at_time(Time.zone.now).select(:id)
  end
end

app/views/dashboard/_attendance_status_and_action.html.erb
<% attendance = attendance_check.attendance %>
<% calendar_event = attendance_check.calendar_event %>

<%= icon_for_status(attendance.status) %>
<%= t("dashboard.show.attendance_status.#{attendance.status}") %>

<br>

<% if attendance_check.can_create_signup? %>
  <%= button_to t('dashboard.show.calendar_events.attendance.submit'), calendar_event_attendance_attendance_path(calendar_event), method: :post, class: 'btn btn-secondary' %>
<% elsif attendance_check.can_create_excuse? %>
  <%= link_to t('dashboard.show.calendar_events.attendance.new'), new_calendar_event_attendance_excuse_path(calendar_event), class: 'btn btn-primary' %>
<% end %>

app/views/dashboard/show.html.erb
<% content_for :title, t('.title') %>

<% if @info.present? %>
  <div class="<%= @info.kind %>">
    <p>
      <b><%= @info.title %></b>
    </p>
    <%= @info.description %>
  </div>
<% end %>

<% unless current_user.profile_complete? %>
  <div>
    <%= t('.profile_completeness.message') %>
    <%= link_to t('.profile_completeness.link'), edit_user_path(current_user) %>
  </div>
<% end %>

<%= render 'search_form' %>

<h2><%= t('.upcoming_birthdays.title') %></h2>

<p><%= t('.upcoming_birthdays.description') %></p>
<ul>
  <% @upcoming_birthdays.each do |user, next_birthday| %>
    <li>
      <%= l next_birthday %>: <b><%= user.full_name %></b>
    </li>
  <% end %>
</ul>

<h2><%= t('.calendar.title') %></h2>

<table>
  <thead>
    <tr>
      <% @overview_calendar_events.each do |calendar_event| %>
        <th class="<%= calendar_event_color_class(calendar_event) %>">
          <%= link_to_if policy(calendar_event).show?, calendar_event.date, calendar_event %>
        </th>
      <% end %>
    </tr>
  </thead>
  
  <tbody class="border-r-2">
    <tr>
      <% @overview_calendar_events.each do |calendar_event| %>
        <td class="text-center">
          <%= attendance_action_symbol(calendar_event) %>
        </td>
      <% end %>
    </tr>
  </tbody>
</table>

<% if params[:load_past] != 'true' %>
  <div class="mt-10">
    <%= link_to t('.load_past'), {load_past: true} %>
  </div>
<% end %>

<% @calendar_events.each do |calendar_event| %>
  <div class="my-5 p-2 border-solid border-primary border-2 rounded bg-gray <%= calendar_event_color_class(calendar_event) %>">
    <p class="font-bold">
      <% if policy(Attendance).index? %>
        <%= link_to calendar_event do %>
          <%= calendar_event.summary %>
        <% end %>
      <% else %>
        <%= calendar_event.summary %>
      <% end %>
    </p>
    <%= render calendar_event %>

    <%= render 'attendance_status_and_action', attendance_check: @attendance_checks[calendar_event] %>
  </div>
<% end %>

<% if policy(:calendar_sync).create? %>
  <%= button_to t('.calendar_events.sync'), calendar_events_syncs_path, method: :post, class: 'btn btn-primary' %>
<% end %>