config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  root 'dashboard#show'

  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker

  passwordless_for :users, controller: 'sessions'

  constraints Passwordless::Constraint.new(User) do # rubocop:disable Metrics/BlockLength
    get 'dashboard' => 'dashboard#show'

    resources :users, except: :destroy do
      resources :user_statuses, except: %i[index show]
    end

    resources :attendances, only: %i[index edit new create update] do
      patch :quick_update
    end

    resource :attendance do
      post :quick_create
    end

    namespace :calendar_events do
      resource :syncs, only: :create
    end

    resources :calendar_events, only: [:show] do
      resource :attendance, only: [] do
        resources :excuses, only: %i[new create], controller: 'calendar_events/attendances/excuses' do
          post :accept
        end
        resource :attendance, only: :create, controller: 'calendar_events/attendances/attendances'
      end
    end

    resources :song_lists do
      resources :song_list_items
      resources :song_media_bundle_downloads, only: %i[create show]

      resources :programs, only: %i[create destroy]
    end

    resources :songs do
      resources :song_media, only: %i[new create destroy]
      resource :score, only: %i[new create edit update destroy]
    end

    resources :name_guesses, only: %i[new create]

    resources :feedbacks, only: %i[new create]

    resources :profiles, only: :index

    resources :statistics, only: :index

    resources :infos, except: %i[destroy show]

    resource :search, only: :show

    mount MissionControl::Jobs::Engine, at: '/jobs'
  end

  get '*path' => redirect('/users/sign_in'), via: :all, constraints: lambda { |req|
    req.path.exclude? 'rails/'
  }
end

app/models/score.rb
# frozen_string_literal: true

class Score < ApplicationRecord
  belongs_to :song

  has_one_attached :file
  validates :file, presence: true
  validates :metadata, presence: true
end

app/controllers/scores_controller.rb
# frozen_string_literal: true

class ScoresController < ApplicationController
  def new
    @score = authorize Score.new(song_id: params[:song_id])
  end

  def edit
    @score = authorize Score.find_by(song_id: params[:song_id])
  end

  def create
    @score = authorize Score.new(score_params)

    if @score.save
      flash.notice = t('.success')
      redirect_to song_path(@score.song)
    else
      flash.alert = t('.error')
      render :new, status: :unprocessable_content
    end
  end

  def update
    @score = authorize Score.find_by(song_id: params[:song_id])

    if @score.update(score_params)
      flash.notice = t('.success')
      redirect_to song_path(@score.song)
    else
      flash.alert = t('.error')
      render :edit, status: :unprocessable_content
    end
  end

  private

  def score_params
    params.expect(score: %i[song_id file metadata])
  end
end

app/views/scores/_form.html.erb
<%= render 'errors', model: @score %>

<%= form_for @score, url: song_score_path(@score.song, @score) do |f| %>
  <%= f.hidden_field :song_id %>

  <div class="form-field">
    <p><%= f.label :file %> <%# i18n-tasks-use t('activerecord.attributes.score.file') %></p>
    <p><%= f.file_field :file, accept: 'application/vnd.mei+xml' %></p>
  </div>

  <div class="form-field">
    <p><%= f.label :metadata %> <%# i18n-tasks-use t('activerecord.attributes.score.metadata') %></p>
    <p><%= f.textarea :metadata %></p>
  </div>

  <p><%= f.submit class: 'btn btn-primary' %>  <%# i18n-tasks-use t('helpers.submit.score.create') %></p>
<% end %>

app/views/scores/edit.html.erb
<% content_for :title, t('.title') %>

<%= render 'form' %>

app/views/scores/new.html.erb
<% content_for :title, t('.title') %>

<%= render 'form' %>