config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  root 'dashboard#show'

  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker

  passwordless_for :users, controller: 'sessions'

  constraints Passwordless::Constraint.new(User) do # rubocop:disable Metrics/BlockLength
    get 'dashboard' => 'dashboard#show'

    resources :users, except: :destroy do
      resources :user_statuses, except: %i[index show]
    end

    resources :attendances, only: %i[index edit new create update] do
      patch :quick_update
    end

    resource :attendance do
      post :quick_create
    end

    namespace :calendar_events do
      resource :syncs, only: :create
    end

    resources :calendar_events, only: [:show] do
      resource :attendance, only: [] do
        resources :excuses, only: %i[new create], controller: 'calendar_events/attendances/excuses' do
          post :accept
        end
        resource :attendance, only: :create, controller: 'calendar_events/attendances/attendances'
      end
    end

    resources :song_lists do
      resources :song_list_items
      resources :song_media_bundle_downloads, only: %i[create show]

      resources :programs, only: %i[create destroy]
    end

    resources :songs do
      resources :song_media, only: %i[new create destroy]
      resource :score, only: %i[new create edit update destroy]
    end

    resources :name_guesses, only: %i[new create]

    resources :feedbacks, only: %i[new create]

    resources :profiles, only: :index

    resources :statistics, only: :index

    resources :infos, except: %i[destroy show]

    resource :search, only: :show

    mount MissionControl::Jobs::Engine, at: '/jobs'
  end

  get '*path' => redirect('/users/sign_in'), via: :all, constraints: lambda { |req|
    req.path.exclude? 'rails/'
  }
end

app/models/song_list.rb
# frozen_string_literal: true

class SongList < ApplicationRecord
  has_many :song_list_items, dependent: :destroy
  has_many :song_media_bundle_downloads, dependent: :destroy

  validates :name, presence: true

  enum :status, { in_preparation: 'in_preparation', active: 'active', archived: 'archived' }, default: :in_preparation

  has_many :programs, dependent: :destroy
  has_many :calendar_events, through: :programs
  has_many :songs, through: :song_list_items

  def next_order_number
    (song_list_items.pluck(:order).max || 0) + 1
  end

  def last_updated_at
    return updated_at if song_list_items.none?

    song_list_items.pluck(:updated_at).union(song_list_items.joins(:song).pluck('songs.updated_at')).max
  end
end

app/controllers/song_lists_controller.rb
# frozen_string_literal: true

class SongListsController < ApplicationController
  def index
    @song_lists = policy_scope(SongList)
  end

  def show
    @song_list = policy_scope(SongList).includes(:song_list_items).find(params[:id])
  end

  def new
    @song_list = authorize SongList.new
  end

  def edit
    @song_list = authorize SongList.find(params[:id])
    @program = authorize Program.new(song_list: @song_list)
  end

  def create
    @song_list = authorize SongList.new(song_list_params)

    if @song_list.save
      flash.notice = t('.success')
      redirect_to song_lists_path
    else
      flash.alert = t('.error')
      render :new, status: :unprocessable_content
    end
  end

  def update
    @song_list = authorize SongList.find(params[:id])

    if @song_list.update(song_list_params)
      flash.notice = t('.success')
      redirect_to song_lists_path
    else
      flash.alert = t('.error')
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    song_list = authorize SongList.find(params[:id])

    if song_list.destroy
      flash.notice = t('.success')
      redirect_to song_lists_path
    else
      flash.alert = t('.error')
      render :edit, status: :unprocessable_content
    end
  end

  private

  def song_list_params
    params.expect(song_list: %i[name status calendar_event_id])
  end
end

app/helpers/song_lists_helper.rb
# frozen_string_literal: true

module SongListsHelper
  def song_list_status_options
    SongList.statuses.values.map { |r| [t("activerecord.attributes.song_list.enums.status.#{r}"), r] }
  end

  def song_list_calendar_event_options
    CalendarEvent.future.map { |ce| [ce.date_and_summary, ce.id] }
  end
end

app/views/song_lists/_data_cells.html.erb
<td><%= index + 1 %></td>

<td>
  <% if song_list_item.song? %>
    <%= link_to song_list_item.song do %>
      <%= song_list_item_icon(song_list_item) %>
      <%= song_list_item.display_name %>
    <% end %>
  <% else %>
    <%= song_list_item_icon(song_list_item) %>
    <%= song_list_item.display_name %>
  <% end %>
</td>

<td><%= simple_format(song_list_item.notes) %></td>

app/views/song_lists/_form.html.erb
<%= render 'errors', model: @song_list %>

<%= form_for @song_list do |f| %>
  <div class="form-field">
    <p>
      <%= f.label :name %>
      <%# i18n-tasks-use t('activerecord.attributes.song_list.name') %> *
    </p>

    <p><%= f.text_field :name %></p>
  </div>

  <div class="form-field">
    <p>
      <%= f.label :status %>
      <%# i18n-tasks-use t('activerecord.attributes.song_list.status') %> *
    </p>

    <%= f.select :status, song_list_status_options %>

    <p class="field-hint"><%= t('.status.hint') %></p>
  </div>

  <p><%= f.submit class: 'btn btn-primary' %></p>

  <%# i18n-tasks-use t('helpers.submit.song_list.create') %>
  <%# i18n-tasks-use t('helpers.submit.song_list.update') %>
<% end %>

<% unless @song_list.new_record? %>
  <%= render 'program_form' %>
<% end %>

app/views/song_lists/_program_form.html.erb
<h2><%= t('.programs.title') %></h2>

<% if @song_list.programs.any? %>
  <table>
    <thead>
      <tr>
        <th><%= t('.date_and_summary') %></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @song_list.programs.each do |program| %>
        <tr>
          <td><%= program.calendar_event.date_and_summary %></td>

          <td>
            <% if policy(program).destroy? %>
              <%= button_to t('.destroy'), song_list_program_path(program.song_list, program), method: :delete, class: 'btn btn-danger' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= form_for [@song_list, @program], html: {class: 'mt-5'} do |f| %>
  <%= f.hidden_field :song_list_id %>

  <div class="form-field">
    <p><%= f.label :calendar_event_id, t('.calendar_event_id') %></p>

    <%= f.select :calendar_event_id, song_list_calendar_event_options, include_blank: true %>

    <p class="field-hint"><%= t('.calendar_event.hint') %></p>
  </div>

  <p><%= f.submit class: 'btn btn-primary' %></p>

  <%# i18n-tasks-use t('helpers.submit.program.create') %>
<% end %>

app/views/song_lists/index.html.erb
<% content_for :title, t('.title') %>

<p><%= link_to t('.all_songs'), songs_path %></p>

<% if policy(SongList).new? %>
  <%= link_to t('.new'), new_song_list_path, class: 'btn btn-primary' %>
<% end %>

<table>
  <thead>
    <tr class="sticky top-0">
      <th><%= t('activerecord.attributes.song_list.name') %></th>
      <th><%= t('.song_list.calendar_events') %></th>

      <% if policy(SongList).edit? %>
        <th><%= t('activerecord.attributes.song_list.status') %></th>
      <% end %>

      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @song_lists.each do |song_list| %>
      <tr>
        <td><%= link_to song_list.name, song_list %></td>

        <td>
          <ul>
            <% song_list.calendar_events.each do |calendar_event| %>
              <li><%= calendar_event.date_and_summary %></li>
            <% end %>
          </ul>
        </td>

        <% if policy(song_list).edit? %>
          <td>
            <%= t("activerecord.attributes.song_list.enums.status.#{song_list.status}") %>
          </td>
        <% end %>

        <td>
          <% if policy(song_list).edit? %>
            <%= link_to t('.edit'), edit_song_list_path(song_list), class: 'btn btn-primary' %>
          <% end %>
        </td>

        <td>
          <% if policy(song_list).destroy? %>
            <%= button_to t('.destroy'), song_list_path(song_list), method: :delete, class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/song_lists/show.html.erb
<% content_for :title, @song_list.name %>

<% if policy(SongMediaBundleDownload).create? %>
  <%= button_to t('.song_media_bundle_download.create'), song_list_song_media_bundle_downloads_path(@song_list), class: 'btn btn-secondary' %>
<% end %>

<% if policy(SongListItem).new? %>
  <%= link_to t('.new'), new_song_list_song_list_item_path(@song_list), class: 'btn btn-primary' %>
<% end %>

<table>
  <thead>
    <tr>
      <% if policy(@song_list).edit? %>
        <th></th>
        <th></th>
        <th><%= t('.name') %></th>
        <th><%= t('.notes') %></th>
        <th></th>
        <th></th>
      <% else %>
        <th></th>
        <th><%= t('.name') %></th>
        <th><%= t('.notes') %></th>
      <% end %>
    </tr>
  </thead>

  <tbody
    <% if policy(@song_list).edit? %>
      data-controller="sortable"
      data-sortable-animation-value="150"
      data-sortable-resource-name-value="song_list_item"
      data-sortable-handle-value=".handle"
    <% end %>
  >
    <% @song_list.song_list_items.order(:position).each.with_index do |song_list_item, index| %>
      <% if policy(@song_list).edit? %>
        <tr
          data-sortable-update-url="<%= song_list_song_list_item_path(song_list_item.song_list, song_list_item) %>"
        >
          <td>
            <%= tabler_icon :arrows_move_vertical, classes: ['cursor-move', 'handle'] %>
          </td>

          <%= render 'data_cells', song_list_item: song_list_item, index: index %>

          <td>
            <%= link_to t('.edit'), edit_song_list_song_list_item_path(song_list_item.song_list, song_list_item), class: 'btn btn-primary' %>
          </td>

          <td>
            <% if policy(song_list_item).destroy? %>
              <%= button_to t('.destroy'), song_list_song_list_item_path(song_list_item.song_list, song_list_item), method: :delete, class: 'btn btn-danger' %>
            <% end %>
          </td>
        </tr>
      <% else %>
        <tr>
          <%= render 'data_cells', song_list_item: song_list_item, index: index %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>