config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  root 'dashboard#show'

  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker

  passwordless_for :users, controller: 'sessions'

  constraints Passwordless::Constraint.new(User) do # rubocop:disable Metrics/BlockLength
    get 'dashboard' => 'dashboard#show'

    resources :users, except: :destroy do
      resources :user_statuses, except: %i[index show]
    end

    resources :attendances, only: %i[index edit new create update] do
      patch :quick_update
    end

    resource :attendance do
      post :quick_create
    end

    namespace :calendar_events do
      resource :syncs, only: :create
    end

    resources :calendar_events, only: [:show] do
      resource :attendance, only: [] do
        resources :excuses, only: %i[new create], controller: 'calendar_events/attendances/excuses' do
          post :accept
        end
        resource :attendance, only: :create, controller: 'calendar_events/attendances/attendances'
      end
    end

    resources :song_lists do
      resources :song_list_items
      resources :song_media_bundle_downloads, only: %i[create show]

      resources :programs, only: %i[create destroy]
    end

    resources :songs do
      resources :song_media, only: %i[new create destroy]
      resource :score, only: %i[new create edit update destroy]
    end

    resources :name_guesses, only: %i[new create]

    resources :feedbacks, only: %i[new create]

    resources :profiles, only: :index

    resources :statistics, only: :index

    resources :infos, except: %i[destroy show]

    resource :search, only: :show

    mount MissionControl::Jobs::Engine, at: '/jobs'
  end

  get '*path' => redirect('/users/sign_in'), via: :all, constraints: lambda { |req|
    req.path.exclude? 'rails/'
  }
end

app/models/info.rb
# frozen_string_literal: true

class Info < ApplicationRecord
  KIND_NOTICE = 'notice'
  KIND_ALERT = 'alert'
  KINDS = [KIND_NOTICE, KIND_ALERT].freeze

  validates :title, :description, :kind, presence: true
  validates :kind, inclusion: KINDS

  scope :newest, -> { order(updated_at: :desc) }
  scope :active, -> { where(active: true) }
  scope :newest_active, -> { active.newest }
end

app/controllers/infos_controller.rb
# frozen_string_literal: true

class InfosController < ApplicationController
  def index
    @infos = authorize Info.newest
  end

  def new
    @info = authorize Info.new(active: true)
  end

  def edit
    @info = authorize Info.find(params[:id])
  end

  def create
    @info = authorize Info.new(info_params)

    if @info.save
      flash.notice = t('.success')
      redirect_to root_path
    else
      flash.alert = t('.error')
      render :new, status: :unprocessable_content
    end
  end

  def update
    @info = authorize Info.find(params[:id])

    if @info.update(info_params)
      flash.notice = t('.success')
      redirect_to root_path
    else
      flash.alert = t('.error')
      render :new, status: :unprocessable_content
    end
  end

  private

  def info_params
    params.expect(info: %i[title description kind active])
  end
end

app/helpers/infos_helper.rb
# frozen_string_literal: true

module InfosHelper
  def infos_kind_options
    Info::KINDS.map { |r| [t("activerecord.attributes.info.enums.kind.#{r}"), r] }
  end
end

app/views/infos/_form.html.erb
<%= render 'errors', model: @info %>

<%= form_for @info do |f| %>
  <div class="form-field">
    <p><%= f.label :title %> <%# i18n-tasks-use t('activerecord.attributes.info.title') %> *</p>
    <p><%= f.text_field :title %></p>
  </div>

  <div class="form-field">
    <p><%= f.label :description %> <%# i18n-tasks-use t('activerecord.attributes.info.description') %> *</p>
    <p><%= f.text_field :description %></p>
  </div>

  <div class="form-field">
    <p><%= f.label :kind %> <%# i18n-tasks-use t('activerecord.attributes.info.kind') %></p>
    <%= f.select :kind, infos_kind_options %>
  </div>

  <div class="form-field">
    <p><%= f.label :active %> <%# i18n-tasks-use t('activerecord.attributes.info.active') %></p>
    <p><%= f.check_box :active %></p>
  </div>

  <p><%= f.submit class: 'btn btn-primary' %></p>
<% end %>

app/views/infos/index.html.erb
<% content_for :title, t('.title') %>

<% if policy(Info).new? %>
  <%= link_to t('.new'), new_info_path, class: 'btn btn-primary' %>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= t('.title') %></th>
      <th><%= t('.description') %></th>
      <th><%= t('.kind') %></th>
      <th><%= t('.active') %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @infos.each do |info| %>
      <tr>
        <td>
          <%= info.title %>
        </td>
        <td>
          <%= info.description %>
        </td>
        <td>
          <%= info.kind %>
        </td>
        <td>
          <%= boolean_emoji(info.active?) %>
        </td>
        <td>
          <% if policy(info).edit? %>
            <%= link_to t('.edit'), edit_info_path(info), class: 'btn btn-primary' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>